version: '3'
services:

  flask:
    image: python:3.8-alpine
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./api:/app/api
      - ./react-app:/app/react-app
    command: sh -c "apk add binutils libc-dev && cd app/api && pip install -r requirements.txt && gunicorn --bind 0.0.0.0:5000 wsgi"

  ghost:
    image: ghost:latest
    restart: always
    ports:
      - "2368:2368"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      url: ${GHOST_URL}
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${DB_PASS}
      database__connection__database: ghost
    volumes:
      - ./ghost/ghost_content:/var/lib/ghost/content

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./ghost/ghost_mysql:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - ghost
      - flask
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./nginx/letsencrypt/:/etc/letsencrypt/
      - ./nginx/html/:/usr/share/nginx/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/